{% set name = "langchain-prompty" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_prompty-{{ version }}.tar.gz
  sha256: c721052bb32c61ca747d7e63bb77a9c9ab9f5a8c429b7286bc12d088abe9a039

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core <0.4.0,>=0.3.0
    - pyyaml >=6.0.1,<7.0.0
    - types-pyyaml >=6.0.12,<7.0.0

test:
  imports:
    - langchain_prompty
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Prompty and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
